#!/usr/bin/env bash
set -x
set -euo pipefail
trap "kill 0" SIGINT

tmp=$(mktemp -d)
echo "$tmp"
cd "$tmp"
python -m http.server 1500 &

readarray -t files < "$1"
count=${#files[@]}
n=0
next() {
	while [ ! -f "${files[$n]}" ]; do
		n=$(( ( $n + 1 ) % $count ))
	done
	echo "Loading ${files[$n]} to cur.pic" >&2
	ln -s "$(realpath "${files[$n]}")" $tmp/cur.pic
	n=$(( ( $n + 1 ) % $count ))
}

next

while true; do
	read
	rm $tmp/cur.pic
	next
	echo
done | ncat -l 1501 --send-only -k
